### ISSUE TITLE
I am getting error while using matrixsdk. Do you have a latest version of this

### ISSUE THREAD

**Issue by Dhannuu** [niochat/MatrixSDK#4]
Failed to build module 'MatrixSDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)', while this compiler is 'Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)'). Please select a toolchain which matches the SDK.

**Comment by kiliankoe** [comment]
Hi @Dhannuu, this hasn't been updated in a while and I'd recommend against using it. You should go with the new Rust-based SDK, which can also be used from a Swift app directly, see https://github.com/matrix-org/matrix-rust-components-swift
